### ISSUE TITLE
Лаба 2

### ISSUE THREAD

**Issue by irinamatveeva** [sofya365/laby#2]
Хорошим тоном считается запись всех sql команд заглавными буквами, а все остальное малыми. Например, в задании 1 должно быть SELECT ... FROM.... 
Задание 5 - условие "не превышающий", то есть <= , а не <
Задание 7 - выбирать нужно "объекты" с искомыми id, а не сами id, также рекомендуется OR использовать IN(....)
Задание 9 - нужно выбрать не все букинги (аренду), а пользователей. Их не так много
Задание 11 - не сделано.
Задание 12 - нужно найти дату последней регистрации члена клуба, а не брони объекта.
Задание 13 - то же самое.
Задание 14 - надо бы наверно подписать, какой самый дорогой и какой самый дешевый. И точно ли нужно использовать initialoutlay?

**Comment by lasbio** [comment]
Лабораторная удалена?

**Comment by sofya365** [comment]
я хотела загрузить заново 2 лабораторную

**Comment by sofya365** [comment]
> Хорошим тоном считается запись всех команд sql заглавными буквами, а все остальное малыми. Например, в задании 1 должно быть ВЫБРАТЬ ... ИЗ.... Задание 5 - условие "не превышающий", то есть <= , а не < Задание 7 - выбрать нужные "объекты" с искими идентификаторами, а не самими идентификаторами, Также рекомендуется ИЛИ использовать IN(....) Задание 9 - нужно выбрать не все бронирования (аренду), а пользователей. Их не так много Задание 11 - не сделано. Задание 12 - необходимо найти последнюю регистрацию члена клуба, а не брони. Задание 13 - то же самое. Задание 14 - надо бы наверное написать, какой самый дорогой и какой самый дешевый. И точно ли нужно использовать InitialOutlay?

вторую лабораторную загрузила с учетом всех ошибок

**Comment by lasbio** [comment]
Объясните зачем Вы удаляете и загружаете файлы вручную? Все должно делаться через git.

**Comment by sofya365** [comment]
> Объясните зачем Вы удаляете и загружаете файлы вручную? Все должно делаться через git.

надеюсь, исправлено верно, впредь буду делать через git
