### ISSUE TITLE
lab-4

### ISSUE THREAD

**Issue by sofya365** [sofya365/laby#4]
загрузила некоторые задания 4 лабораторной

**Comment by lasbio** [comment]
пустые файлы !?

**Comment by sofya365** [comment]
> пустые файлы !?

извините, это какая то ошибка, загрузила файлы еще раз

**Comment by lasbio** [comment]
3 - поскольку все данные уже есть в базе, они зарегистрированы ранее, то вы их должны использовать, а не писать значения вручную. Кроме этого, в задании указано, что надо сгенерировать ID ( == facid), а не задавать его вручную. 
6 - в задании не указаны старые цены. Сказано увеличить на 10%. Что будет если вам надо будет увеличивать на 10% каждые полгода. Каждый раз новый скрипт писать?

**Comment by sofya365** [comment]
> 3 - поскольку все данные уже есть в базе, они зарегистрированы ранее, то вы их должны использовать, а не писать значения вручную. Кроме этого, в задании указано, что надо сгенерировать ID ( == facid), а не задавать его вручную. 6 - в задании не указаны старые цены. Сказано увеличить на 10%. Что будет если вам надо будет увеличивать на 10% каждые полгода. Каждый раз новый скрипт писать?

загрузила 3 и 6

**Comment by lasbio** [comment]
3 - 'Spa', 20, 30, 100000, 800 уже есть в базе данных
6 - зачем делать лишнее действие +?

**Comment by sofya365** [comment]
> 3 - 'Spa', 20, 30, 100000, 800 уже есть в базе данных 6 - зачем делать лишнее действие +?

загрузила 6, а в 3 я добавила spa с теми же характеристиками только с новым facid

**Comment by lasbio** [comment]
3 - не выполнено условие задания "сгенерировав новое ID".  В задании есть единственное параметр, который и надо использовать - это 'spa'.

**Comment by sofya365** [comment]
> 3 - не выполнено условие задания "сгенерировав новое ID". В задании есть единственное параметр, который и надо использовать - это 'spa'.

3 исправила

**Comment by lasbio** [comment]
3 - попробуйте запустить ваш скрипт дважды и вы увидите, что будет возникать ошибка.

**Comment by sofya365** [comment]
> 3 - попробуйте запустить ваш скрипт дважды и вы увидите, что будет возникать ошибка.

загрузила 3
